# Generated by Django 5.0.6 on 2024-05-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songs_music_songs_id_8977f4_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='songs',
            name='listened',
        ),
    ]
