# Generated by Django 5.0.6 on 2024-05-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_songs_options_remove_songs_listened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='songs',
            name='music_songs_id_8977f4_idx',
        ),
    ]
