# Generated by Django 5.0.6 on 2024-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_songs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='listened',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
