# Generated by Django 5.0.6 on 2024-05-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_songs_listened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['id']},
        ),
    ]
